language: node_js
node_js:
- 4.2.3
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
after_script: source ./scripts/sonar.sh
before_deploy: source ./scripts/pre-release.sh
deploy:
  provider: releases
  skip_cleanup: true
  file: nodejs-getting-started-$BUILD_VERSION.tar.gz
  on:
    tags: false
    all_branches: true
    condition: "$TRAVIS_BRANCH = $PRE_RELEASE_BRANCH || $TRAVIS_BRANCH = $RELEASE_BRANCH"
  api_key:
    secure: FvyiRe+uH2Zkvto+yi9O0nvHBOxZ8qnevUIv3wYmYtqF9T5G+0kpLfPjh0APnohPKbK7ck/sb2qReMtg89o2/otM5m1AaDEa92VdSnAKMqVIPw6Rumit7adskFlY2l7GuHB03d4fu86N6XNqz2nchKyoLBfiEWSqwqgPGTU8HV38zGrCPhtvFAtjSD/TyvskDrZM1RlKsnTTtUPuDTYFg59PuLj4LUQh2cJpg+VMaofceSou7KPsQdBHgKdGSgyGKIv/XjS62GZLrTktc8Y2vEAxxgbqCS2j0XdPPgC9z4dO03OkStkDY7v+oFPUTeNTtlHzwtybECCgUEIlzYJ8wv3lOHgdLIIqde4uwOJPPnziJKf4oGN090A1EFfMJX+vKn24fkbnrCb4Gl9xt5aw0Mo1y/RJXcWAP2Le3IoKaJ1LX47tviL62qoqeon5gX1FilOFwAFlqn6DvqjYQA1FIG1e6pZgZt7KxETNKbQ1WpAdTTslnOnXA5vwGLH3wEdWENMQFH2WnWdD13wxvrIsG8aPKDwUw82xd901p8mHpH5Ls5gk3iv5clwF+0U92L/PLTlEmMlcyE8i7606uC9BiPLItqfJ6UR95EpnDNw8LmQfrpcrkugEVQha8qjn1aWokRRURBmQ178IOyXgtGFR/uFZtrbOk8dQTCSCOXzF/20=
env:
  global:
  - PRE_RELEASE_BRANCH=dev
  - RELEASE_BRANCH=master
  - SONAR_HOST_URL=https://sonar.appsluiza.com.br/
  - secure: VGSA/pXHvU/GYfQLmCuqBfox0uX7ZJAFi0HATT/FfpZ5/TJS7UkfSHmYAVau93aGNYbOebved6fe8DTfMFyA9RjCuyql4TiOUgOYJzPLKhS9adlqi5wA5MPKfNqKOL75OdjfFph8Wdfp2fs7fkvuUw5pN5CsQhmO9oEt81Xfu2AEG34UUc8CkSIBWPM4Cqjb6ZfN8CluAo6nxwbACHXHuQ7BgPkCKnGpNCXLV96ZSbmQyE5zUuOdamNQLAkJAogDAORvT7KIsN9Gga+WajsO4wgWAYy+1t1U+hubhiVreoldvMqp4jdsNhNGhmEvtTt+9yLm051Z1Z+wH3Y6zox/8rF9OOPuDUxIVn+lg6Ms0Y2yZfV4jkJZRW8xhoPfYOdZPXs7dijSsO9ZpmPjDtzvSAEDxc5yLe32OSvxdOELf2VwrAujqIRKWmOLuKMqe5df7sJWjtRS1M/N4Wcdk4gQqvn0+SbijFzLRFio80OSjl7GeiVd1iRIvl1TpxXOoRL0hXySWUyQjXiUMNFKFzaOImF0qP3RDyF0sVTTPQkUFu/A3VFATyHMN7CqyIH2lFVCHS4XALvevTdSgDGGkgx4IqG3AUiv6TYQbYHOGJL2hdKBczBDmoJC+54ahDXcnLl24j0aRADcn8sbidUuknQ5Wo4lk0NYZHfCHftOq37LQcw=
  - secure: cIOAqdEzzzZdoh/4QbDU7mcN9plAgwJ278O4ZzXEhKUfQ5LCPlitrL6JXWQ11c2sqISUIf+c6idppzhXx2RaEX46pTH4/6vDWMg7J0MSMLPnLKc3pbxK+Dm8XVI3ZJ6hQe3guNonho+rW7OsBDQk+C/jnoVPn6AKbJQfM8zz7nFHUxQP6r4HM2WcAIs/xwtq3Qk0Pnc7eve1ZHIaUahrFW5cH46cLeqmrpAvpIARxfk6IC1ELeXXljMLhWH8EGcH+Mh7JC1v7tcEOGZoy+UHoBxjPgKJOu66Np8Jby+xnTuP1j9Y3qhNm8BDgE4TargG/4oqWEt9Q6lfGCGnIx2yGZNWKsMFXrRCHCvb2Xsy7+oFiWuK5KUh/qAbN03TDNlm7nZt+TNQFcj91q4DplD/A1/s6zX1UPcCxPH2+djQUYwfTD1WNzwEX+i7nRZqeBEhgrDMsaO6RrUXkFxMQbM0mkH6okMBTLhJEp+STyHszUNT2VTobka5RHeAl66M1i1eIIKmXi3iqNjrf/cMYSuD9wHgMHZUCwXV+uafwuTz8qgl1ozB1fBZzSfiMNEi9VDnUCnD5peBLDjjVaGBwto8RLdRTUaDvVYkDIP8CIMvCarvk6HqJ4LgqfRniRyh/9lvtkjtK+vpHZn7QhdTNXfvZcxLrilF3qHV2B7omirNVrA=
